{% set name = "glcontext" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moderngl/glcontext/archive/{{ version }}.tar.gz
  sha256: dea6398cdf161ce02be442cd1bbb75cf8f4f7c3e09f803ebe6d516db5def68e9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools

    - xorg-libx11                        # [linux]
    - xorg-xorgproto                     # [linux]
    - libegl-devel                       # [linux]
    - libgl-devel                         # [linux]
  run:
    - python

test:
  imports:
    - glcontext

about:
  home: https://github.com/moderngl/glcontext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library providing OpenGL implementation for ModernGL on multiple platforms.

extra:
  recipe-maintainers:
    - pavelzw
    - patricksnape
