{% set name = "glcontext" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moderngl/glcontext/archive/{{ version }}.tar.gz
  sha256: 69ff64297e571d35d26764f9395404a3ecb1b40885cbe1d69e2cd641293a2b21

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-libgl-devel') }}       # [linux]

  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - glcontext

about:
  home: https://github.com/moderngl/glcontext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library providing OpenGL implementation for ModernGL on multiple platforms.

extra:
  recipe-maintainers:
    - pavelzw
    - patricksnape
