{% set name = "glcontext" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moderngl/glcontext/archive/{{ version }}.tar.gz
  sha256: 757f36ce8c72d81d871a57580a41e3298bb3f31b70e6d7a5795b96b1820e5d37

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]

  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - glcontext

about:
  home: https://github.com/moderngl/glcontext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library providing OpenGL implementation for ModernGL on multiple platforms.

extra:
  recipe-maintainers:
    - patricksnape
