{% set name = "glcontext" %}
{% set version = "2.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moderngl/glcontext/archive/{{ version }}.tar.gz
  sha256: ba18a7baec5687d7bbb375ddaba101a2131e3436a73ffffba8cb08e530d3c48a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - glcontext

about:
  home: https://github.com/moderngl/glcontext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library providing OpenGL implementation for ModernGL on multiple platforms.

extra:
  recipe-maintainers:
    - patricksnape
