{% set name = "glcontext" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moderngl/glcontext/archive/{{ version }}.tar.gz
  sha256: ba7a05895239671dfa5448715d5cb708881695aad5706503829a11c63fd31a4e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-libgl-devel')}}       # [linux]

  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - glcontext

about:
  home: https://github.com/moderngl/glcontext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library providing OpenGL implementation for ModernGL on multiple platforms.

extra:
  recipe-maintainers:
    - pavelzw
    - patricksnape
